# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
rojo = "rojo-rbx/rojo@7.5.1"
luau-lsp = "JohnnyMorganz/luau-lsp@1.61.0"
selene = "Kampfkarren/selene@0.30.0"